
services:
  # Base de Datos
  postgres-db:
    image: postgres:15
    container_name: postgres_db_transporte
    environment:
      POSTGRES_DB: db_gestion_transporte
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tu_password_de_postgres
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "5432:5432"
    networks:
      - gestion-transporte-net

  # KEYCLOAK 
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: start-dev
    ports:
      - "8081:8080" 
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - gestion-transporte-net

  #bOSRM
  osrm:
    image: ghcr.io/project-osrm/osrm-backend:latest
    container_name: osrm
    ports:
      - "5000:5000"
    networks:
      - gestion-transporte-net
    volumes:
      - ./osrm-data:/data   
    command: osrm-routed /data/argentina-latest.osrm

  # Solicitudes
  servicio-solicitud:
    build:
      context: ./servicio-solicitud
    container_name: servicio_solicitud
    ports:
      - "8082:8082"
    depends_on:
      - postgres-db
      - keycloak   
    networks:
      - gestion-transporte-net
    environment:
      # BD
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/db_gestion_transporte
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tu_password_de_postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  # Transporte
  servicio-transporte:
    build:
      context: ./servicio-transporte
    container_name: servicio_transporte
    ports:
      - "8083:8083"
    depends_on:
      - postgres-db
      - keycloak
    networks:
      - gestion-transporte-net
    environment:
      # BD
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/db_gestion_transporte
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tu_password_de_postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
  
  # Log√≠stica
  servicio-logistica:
    build:
      context: ./servicio-logistica
    container_name: servicio_logistica
    ports:
      - "8084:8084"
    depends_on:
      - postgres-db
      - servicio-solicitud
      - servicio-transporte
      - osrm
      - keycloak
    networks:
      - gestion-transporte-net
    environment:
      # BD
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/db_gestion_transporte
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tu_password_de_postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      API_SERVICIOS_TRANSPORTE: http://servicio-transporte:8083/transporte
      API_SERVICIOS_SOLICITUD: http://servicio-solicitud:8082/solicitudes
      API_SERVICIOS_CONTENEDOR: http://servicio-solicitud:8082/contenedores   

      API_DISTANCIA_URL: http://osrm:5000

  # API GATEWAY
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api_gateway
    ports:
      - "8080:8080"
    depends_on:
      - servicio-solicitud
      - servicio-transporte
      - servicio-logistica
      - keycloak
    networks:
      - gestion-transporte-net
networks:
  gestion-transporte-net:
    driver: bridge

volumes:
  keycloak_data:
