server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

      routes:
        # --- 1. Servicio de Logística ---
        # Tu URL: http://localhost:8084/api/logistica/
        # Docker Service: servicio-logistica (puerto 8084)
        - id: logistica-route
          uri: http://servicio-logistica:8084
          predicates:
            - Path=/api/logistica/**
          # NOTA: No usamos StripPrefix porque tu servicio YA espera recibir "/api/logistica"

        # --- 2. Servicio de Transporte ---
        # Tu URL: http://localhost:8083/transporte
        # Docker Service: servicio-transporte (puerto 8083)
        - id: transporte-route
          uri: http://servicio-transporte:8083
          predicates:
            - Path=/api/transporte/**
          filters:
            # Quitamos "/api" para que al servicio le llegue "/transporte/..."
            - StripPrefix=1

        # --- 3. Servicio de Solicitud ---
        # Tu URL: http://localhost:8082/ (Raíz)
        # Docker Service: servicio-solicitud (puerto 8082)
        - id: solicitud-route
          uri: http://servicio-solicitud:8082
          predicates:
            - Path=/api/solicitudes/**
          filters:
            # Quitamos "/api/solicitudes" (2 partes) para que al servicio le llegue "/" (la raíz)
            - StripPrefix=2
  security:
    oauth2:
      resourceserver:
        jwt:
          # URL interna de Docker para que el Gateway descargue las claves públicas
          # IMPORTANTE: Asegúrate de que coincida con el nombre de tu servicio en docker-compose
          jwk-set-uri: http://keycloak:8080/realms/tpi-backend/protocol/openid-connect/certs
          # Opcional: ayuda a validar que el token vino de quien esperas
          # issuer-uri: http://localhost:8081/realms/TPI-Realm